dist: trusty
language: php
php:
  - 5.5
  - 5.6
  - 7.0

env:
  - TEST_SUITE=unit
  - TEST_SUITE=phpcs

before_script:
  - sleep 60

script:
  - wget https://github.com/magento/magento2/archive/2.1.0.zip
  - unzip -qq 2.1.0.zip
  - cd magento2-2.1.0/